config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
    controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  root to: 'places#index'

  get "places/search", to: "places#search"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :places do
    resources :reservations, only: [ :create ]
    resources :reviews, only:[ :create ]
  end

  resources :users, only: [:show]
  patch "reservations/:id/accept", to: "reservations#accept", as: :reservation_accept
  patch "reservations/:id/decline", to: "reservations#decline", as: :reservation_decline
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/place.rb
class Place < ApplicationRecord
  belongs_to :user
  has_many :reviews, dependent: :destroy
  has_many :reservations, dependent: :destroy
  validates :name, presence: true
  validates :description, presence: true
  validates :address, presence: true
  validates :price, presence: true
  validates :photo, presence: true
  mount_uploader :photo, PhotoUploader

  def rating
    self.reviews.average(:rating).to_i
  end
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :user
  belongs_to :place
  validates :user, presence: true
  validates :place, presence: true

  def accept
    self.status = "accepted"
    save
  end

  def decline
    self.status = "declined"
    save
  end
end

app/models/review.rb
class Review < ApplicationRecord
  RATING = (1..5)
  belongs_to :place
  validates :content, presence: true
  validates :rating, presence: true, inclusion: { in: RATING, allow_nil: false }, numericality: {only_integer: true }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  # after_create :send_welcome_email
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, omniauth_providers: [:facebook]
  has_many :places, dependent: :destroy
  has_many :reservations, dependent: :destroy
  has_many :reviews, through: :places
  mount_uploader :photo, PhotoUploader

def self.find_for_facebook_oauth(auth)
    user_params = auth.to_h.slice(:provider, :uid)
    user_params.merge! auth.info.slice(:email, :first_name, :last_name)
    user_params[:facebook_picture_url] = auth.info.image
    user_params[:token] = auth.credentials.token
    user_params[:token_expiry] = Time.at(auth.credentials.expires_at)

    user = User.where(provider: auth.provider, uid: auth.uid).first
    user ||= User.where(email: auth.info.email).first # User did a regular sign up in the past.
    if user
      user.update(user_params)
    else
      user = User.new(user_params)
      user.password = Devise.friendly_token[0,20]  # Fake password for validation
      user.save
    end

    return user
  end

  def username
    return self.email.split("@")[0].capitalize
  end

  def rating
    return self.reviews.average(:rating).to_i
  end

  #private

  #def send_welcome_email
    #UserMailer.welcome(self).deliver_now
 #end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :photo, :photo_cache])
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
  end
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  before_action :set_place, only: [ :edit, :update ]
  skip_before_action :authenticate_user!, only: [:index, :show, :search]

  def index
    @places = Place.all
  end

  def new
    @place = Place.new
  end

  def show
    @place = Place.find(params[:id])
    @review = Review.new
  end

  def create
    @place = Place.new(place_params)
    @place.user = current_user
    if @place.save
      redirect_to place_path(@place)
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @place.update(place_params)
      redirect_to place_path(@place)
    else
      render :edit
    end
  end

  def search
    query = params[:query]
    @places = Place.where("name LIKE ?", "%#{query}%")
  end

  private

  def place_params
    params.require(:place).permit(:name, :description, :address, :price, :photo, :photo_cache, :UV, :startlight, :satellite, :wifi, :earth_mailing, :astronaut_outfit, :crater, :freezing, :alien, :detox)
  end

  def set_place
    @place = Place.find(params[:id])
  end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  skip_before_action :authenticate_user!
  before_action :set_reservation, only: [ :accept, :decline ]
  # user = User.first
  # UserMailer.welcome(user).deliver_now

  def create
    @reservation = Reservation.new
    @reservation.user = current_user
    @reservation.place = Place.find(params[:place_id])
    @reservation.save
    redirect_to user_path(current_user), notice: "Your booking was submitted and it's awaiting confirmation."
  end

  def accept
    @reservation.accept
    redirect_to user_path(@reservation.place.user.id)
  end

  def decline
    @reservation.decline
    redirect_to user_path(@reservation.place.user.id)
  end

  private

  def set_reservation
    @reservation = Reservation.find(params[:id])
  end

  # def reservation_params
  #   params.require(:reservation).permit(:user, :reservation)
  # end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_review, only: [:show, :edit, :update, :destroy]

  def show
  end

  def create
    @place = Place.find(params[:place_id])
    @review = Review.new(review_params)
    @review.place = @place
    if @review.save
      redirect_to place_path(@place)
    else
      render "places/show"
    end
  end

  # def edit
  # end

  # def update
  #   if @review.update(review_params)
  #     redirect_to review_path(@review)
  #   else
  #     redirect_to review_path(@review)
  #   end
  # end

  # def destroy
  #   @review.destroy
  # end


  private
  def review_params
    params.require(:review).permit(:content, :rating)
  end

  def set_review
    @review = Review.find(params[:id])
  end

end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    user = User.find_for_facebook_oauth(request.env['omniauth.auth'])

    if user.persisted?
      sign_in_and_redirect user, event: :authentication
      set_flash_message(:notice, :success, kind: 'Facebook') if is_navigational_format?
    else
      session['devise.facebook_data'] = request.env['omniauth.auth']
      redirect_to new_user_registration_url
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :authenticate_user!, only: :show

  def show
    @user = User.find(params[:id])
    @places = @user.places
    # Reservations for my properties
    @reservations_for_me = @user.places.map { |res| res.reservations }
    @reservations_for_me.flatten!
    # Reservations I made
    @reservations_i_made = @user.reservations
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>Seventh Heaven</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all' %>
  </head>
  <body>
    <%= render 'shared/flashes' %>
    <%= render "shared/navbar" %>
    <%= yield %>
    <%= render "shared/footer" %>
    <script type="text/javascript" src="https://maps.google.com/maps/api/js?key=AIzaSyB_VaqTzefQSGN_OuOLWSWJh-AgHIJCCBM"></script>
    <%= javascript_include_tag 'application' %>
    <%= yield(:after_js) %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/places/_form.html.erb
<div class="banner" style="background-image: url('<%= image_path 'newplaceback.jpg' %>')">
<div class="container" >
<div class="row">
<div class="col-sm-offset-2 col-sm-8 col-md-6 col-md-offset-3">
<div class="form " >
<%= simple_form_for(@place) do |f| %>
<%= f.error_notification %>
  <%= f.input :name, label_html: {class:"h4"} %>
  <%= f.input :description, label_html: {class:"h4"} %>
  <%= f.input :address, label_html: {class:"h4"} %>
  <label class="h4">Features</label>
  <div class="feature-items">
  <div class="row">
    <div class="col-sm-6">
      <%= f.input :UV, label_html: {class: "type"},label: 'UV', as: :boolean, boolean_style: :inline %>
    </div>
    <div class="col-sm-6">
      <%= f.input :startlight, label_html: {class:"type"}, label: 'Shooting star', as: :boolean, boolean_style: :inline %>
    </div>
    <div class="col-sm-6">
      <%= f.input :satellite, label_html: {class:"type"}, label: 'Satellite',as: :boolean, boolean_style: :inline %>
    </div>
    <div class="col-sm-6">
      <%= f.input :wifi, label_html: {class:"type"}, label: 'Wifi', as: :boolean, boolean_style: :inline %>
    </div>
    <div class="col-sm-6">
      <%= f.input :earth_mailing, label_html: {class:"type"}, label: 'Earth mailing', as: :boolean, boolean_style: :inline %>
    </div>
    <div class="col-sm-6">
      <%= f.input :astronaut_outfit, label_html: {class:"type"},label: 'Astronaut outfit', as: :boolean, boolean_style: :inline %>
    </div>
    <div class="col-sm-6">
      <%= f.input :crater, label_html: {class:"type"}, label: 'Crater', as: :boolean, boolean_style: :inline %>
    </div>
    <div class="col-sm-6">
      <%= f.input :alien, label_html: {class:"type"}, label: 'Alien', as: :boolean, boolean_style: :inline %>
    </div>
    <div class="col-sm-6">
      <%= f.input :freezing, label_html: {class:"type"}, label: 'Freezing', as: :boolean, boolean_style: :inline %>
    </div>
    <div class="col-sm-6">
     <%= f.input :detox, label_html: {class:"type"}, label: 'Detox', as: :boolean, boolean_style: :inline %>
    </div>
  </div>
 </div>

 <%= f.input :price, label_html: {class:"h4"} %>
  <%= f.input :photo, label_html: {class:"h4"} %>
  <%= f.input :photo_cache, as: :hidden %>
  <div class="button-wrapper">
    <%= f.submit class: "btn btn-medium " %>
</div>

<% end %>
</div>
</div>
</div>
</div>
</div>

app/views/places/_list.html.erb
<% @places.each do |place| %>
<div class="col-xs-12 col-sm-4 col-md-3">
  <div class="card">
    <div class="card-category">
      <% place.rating.times do %>
        <i class="fa fa-star active-star"></i>
      <% end %>
      <% (5 - place.rating).times do %>
        <i class="fa fa-star inactive-star"></i>
      <% end %>
    </div>


    <div class="card-header" style="background-image: url('<%= cl_image_path place.photo, height: 300, width: 400, crop: :fill %>')">
    </div>


    <div class="card-description">
      <h2><%= place.name %></h2>
      <p>€<%= place.price %></p>
    </div>
    <% avatar_url = place.user.facebook_picture_url || place.user.photo %>
    <%= cl_image_tag avatar_url, class: "card-user avatar" %>
    <%= link_to "", place_path(place), class: "card-link" %>
  </div>
</div>
<% end %>

app/views/places/edit.html.erb
<div class="container">
  <h1>Edit a place</h1>
  <%= render 'form' %>
</div>

app/views/places/index.html.erb
<div id="particles-js" style="background-image: url('<%= image_path 'space-hero.jpg' %>')">
</div>
<div class="hero-wrapper">
  <div class="container">
    <div class="hero-content">
      <div class="banner-content">
        <h1>Rent a place in a galaxy near you</h1>
        <div class="row">
        <div class="col-xs-12 col-sm-8 col-sm-offset-2">
          <form class="form-inline" action="/places/search">
            <div class="form-group">
            <label class="sr-only" for="search">Search</label>
            <input type="text" class="form-control" id="search" name="query" placeholder="Find your dream destination">
            </div>
            <button type="submit" class="btn btn-default btn-lg"><i class="fa fa-search"></i></button>
          </form>
        </div>
        </div>
      </div>
    </div>
  </div>
</div>


<div class="wrapper">
  <div class="container">
    <h1 id="list-title">Places near you</h1>
    <div class="row", id="place-list">
      <%= render "list" %>
    </div>
  </div>
</div>

<div class='button-wrapper'>
<%= link_to 'Add new place', new_place_path(@place), class: "btn btn-lg" %>
</div>

app/views/places/new.html.erb
<%= render 'form', place: @place %>

app/views/places/search.html.erb
<div class="wrapper">
  <div class="container">
  <h1>Search results</h1>
    <div class="row", id="place-list">
      <%= render "list" %>
    </div>
  </div>
</div>

app/views/places/show.html.erb
 <div class="place-photo-wrapper" style= "background-image:linear-gradient(-225deg, rgba(0,101,168,0.6) 0%, rgba(0,36,61,0.6) 50%), url('<%= cl_image_path @place.photo, width: 1500, height: 400, crop: :fill %>')">
   <div class="banner-content">
    <h1><%= @place.name %></h1>
    <p>
      <% @place.rating.times do %>
      <i class="fa fa-star active-star"></i>
      <% end %>
      <% (5 - @place.rating).times do %>
      <i class="fa fa-star inactive-star"></i>
      <% end %>
    </p>
    <div>
      <% if user_signed_in? %>
        <%= link_to place_reservations_path(@place), method: :post, class: "btn btn-transparent btn-lg" do %>
          Book for €<%= @place.price %>
        <% end %>
      <% else %>
        <%= link_to new_user_session_path, class: "btn btn-transparent btn-lg" do %>
          Book for €<%= @place.price %>
        <% end %>
      <% end %>
    </div>
  </div>
</div>


<div class="container">
  <div class="row">
    <div class="col-xs-12 col-md-6">

      <h3>Description</h3>
      <%= @place.description %>

      <h3>Features</h3>
      <div class="row">
        <div class="col-xs-6">
          <ul class="fa-ul">
            <li <%= "class=unsupported" if @place.UV == false %>>
              <i class="fa-li fa fa-sun-o"></i>UV
            </li>
            <li <%= "class=unsupported" if @place.startlight == false %>>
              <i class="fa-li fa fa-star-o"></i><span> Shooting stars</span>
            </li>
            <li <%= "class=unsupported" if @place.satellite == false %>>
              <i class="fa-li fa fa-globe"></i>Satellite</span>
            </li>
            <li <%= "class=unsupported" if @place.wifi == false %>>
              <i class="fa-li fa fa-wifi"></i>Wifi</span>
            </li>
            <li <%= "class=unsupported" if @place.earth_mailing == false %>>
              <i class="fa-li fa fa-envelope-o"></i>Earth mailing</span>
            </li>
          </ul>
        </div>
        <div class="col-xs-6">
          <ul class="fa-ul">
            <li <%= "class=unsupported" if @place.astronaut_outfit == false %>>
              <i class="fa-li fa fa-user-circle-o"></i>Astronaut outfit</span>
            </li>
            <li <%= "class=unsupported" if @place.crater == false %>>
              <i class="fa-li fa fa-circle"></i>Craters</span>
            </li>
            <li <%= "class=unsupported" if @place.freezing == false %>>
              <i class="fa-li fa fa-thermometer-empty"></i>Deep freezing</span>
            </li>
            <li <%= "class=unsupported" if @place.alien == false %>>
              <i class="fa-li fa fa-reddit-alien"></i>Alien</span>
            </li>
            <li <%= "class=unsupported" if @place.detox == false %>>
              <i class="fa-li fa fa-smile-o"></i>Detox</span>
            </li>
          </ul>
        </div>
      </div>

      <h3>Galaxy location</h3>
      <%= @place.address %>

     <div id="map_canvas" style="width: 100%; height: 300px;">map div</div>

   </div>

   <div class="col-xs-12 col-md-6">

    <div class="user-info">
      <% user_avatar_url = @place.user.facebook_picture_url || @place.user.photo %>

      <%= image_tag user_avatar_url, crop: :fill, class: "avatar-large" %>
      <h2><%= link_to @place.user.first_name, user_path(@place.user) %></h2>
      <p><%= @place.user.bio %></p>
    </div>

    <div class="user-details">
     <h2>Place reviews</h2>
     <% @place.reviews.each do |review| %>
     <% review.rating.times do %>
     <i class="fa fa-star active-star"></i>
     <% end %>
     <% (5 - review.rating).times do %>
     <i class="fa fa-star inactive-star"></i>
     <% end %>
     <p><%= review.content %></p>
     <% end %>

     <% if user_signed_in? && current_user.reservations.any? { |reservation| reservation.place == @place && reservation.status == "accepted" } %>

        <h2>Add your review</h2>
        <%= simple_form_for([@place, @review]) do |f| %>
        <%= f.input :rating, collection: Review::RATING, as: :radio_buttons, item_wrapper_class: 'radio-inline' %>
        <%= f.input :content, as: :text, input_html: {rows: 5, cols: 10} %>
        <%= f.submit class: "btn btn-lg"  %>
        <% end %>
    <% end %>

  </div>
</div>
</div>


<div class="padded text-center" >
  <%= link_to "Back to homepage", places_path, class: "btn-medium" %>
</div>

</div>


<% content_for(:after_js) do %>
  <%= javascript_tag do %>


var mapTypes = {};

    // set up the map types

    mapTypes['sky'] = {
      getTileUrl: function(coord, zoom) {
        return getHorizontallyRepeatingTileUrl(coord, zoom, function(coord, zoom) {
          return "http://mw1.google.com/mw-planetary/sky/skytiles_v1/" +
          coord.x + "_" + coord.y + '_' + zoom + '.jpg';

        });
      },
      tileSize: new google.maps.Size(256, 256),
      isPng: false,
      maxZoom: 13,
      radius: 57.2957763671875,
      name: 'Sky',
      credit: 'Image Credit: SDSS, DSS Consortium, NASA/ESA/STScI'
    };

    // Normalizes the tile URL so that tiles repeat across the x axis (horizontally) like the
    // standard Google map tiles.
    function getHorizontallyRepeatingTileUrl(coord, zoom, urlfunc) {
      var y = coord.y;
      var x = coord.x;

      // tile range in one direction range is dependent on zoom level
      // 0 = 1 tile, 1 = 2 tiles, 2 = 4 tiles, 3 = 8 tiles, etc
      var tileRange = 1 << zoom;

      // don't repeat across y-axis (vertically)
      if (y < 0 || y >= tileRange) {
        return null;
      }

      // repeat across x-axis
      if (x < 0 || x >= tileRange) {
        x = (x % tileRange + tileRange) % tileRange;
      }

      return urlfunc({x:x,y:y}, zoom)
    }

    function getMarsTileUrl(baseUrl, coord, zoom) {
      var bound = Math.pow(2, zoom);
      var x = coord.x;
      var y = coord.y;
      var quads = ['t'];

      for (var z = 0; z < zoom; z++) {
        bound = bound / 2;
        if (y < bound) {
          if (x < bound) {
            quads.push('q');
          } else {
            quads.push('r');
            x -= bound;
          }
        } else {
          if (x < bound) {
            quads.push('t');
            y -= bound;
          } else {
            quads.push('s');
            x -= bound;
            y -= bound;
          }
        }
      }

      return baseUrl + quads.join('') + ".jpg";
    }

    var map;
    var mapTypeIds = [];

    // Setup a copyright/credit line, emulating the standard Google style
    var creditNode = document.createElement('div');
    creditNode.id = 'credit-control';
    creditNode.style.fontSize = '11px';
    creditNode.style.fontFamily = 'Arial, sans-serif';
    creditNode.style.margin = '0 2px 2px 0';
    creditNode.style.whitespace = 'nowrap';
    creditNode.index = 0;

    function setCredit(credit) {
      creditNode.innerHTML = credit + ' -';
    }

    function initialize() {

      // push all mapType keys in to a mapTypeId array to set in the mapTypeControlOptions
      for (var key in mapTypes) {
        mapTypeIds.push(key);
      }

      var myLatLng = {lat: -25.2882777, lng: -168.11233330000005};


      var mapOptions = {
        zoom: 10,
        center: new google.maps.LatLng(myLatLng),
        mapTypeControlOptions: {
          mapTypeIds: mapTypeIds,
          style: google.maps.MapTypeControlStyle.DROPDOWN_MENU
        }
      };
      map = new google.maps.Map(document.getElementById("map_canvas"), mapOptions);

      // push the credit/copyright custom control
      map.controls[google.maps.ControlPosition.BOTTOM_RIGHT].push(creditNode);

      // add the new map types to map.mapTypes
      for (key in mapTypes) {
        map.mapTypes.set(key, new google.maps.ImageMapType(mapTypes[key]));
      }

      // handle maptypeid_changed event to set the credit line
      google.maps.event.addListener(map, 'maptypeid_changed', function() {
        setCredit(mapTypes[map.getMapTypeId()].credit);
      });

      // start with the moon map type
      map.setMapTypeId('sky');


      var marker = new google.maps.Marker({
        position: myLatLng,
        map: map,
        title: 'Hello World!'
      });
    }



      initialize();



  <% end %>
<% end %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <span>Seventh Heaven</span>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <!-- Search form -->
    <form action="/places/search" class="navbar-wagon-search">
      <input type="text" class="navbar-wagon-search-input" placeholder="Find a galaxy" name="query">
      <button type="submit" class="navbar-wagon-search-btn">
        <i class="fa fa-search"></i>
      </button>
    </form>

    <!-- Profile picture and dropdown -->
    <% if user_signed_in? %>
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <% avatar_url = current_user.facebook_picture_url || current_user.photo %>
          <%= image_tag avatar_url, class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to user_path(current_user) do %>
                <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
              <% end %>
            </li>

              <li>
                <%= link_to destroy_user_session_path, method: :delete do %>
                  <i class="fa fa-sign-out"></i>  <%= t(".profile", default: "Sign Out") %>
                <% end %>
              </li>
          </ul>
        </div>
      </div>

    <% else %>
    <!-- Button (call-to-action) -->
      <%= link_to t(".top_call_to_action", default: "Log in"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to t(".top_call_to_action", default: "Sign up"), new_user_registration_path, class: "navbar-wagon-item navbar-wagon-button btn" %>
    <% end %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Some mobile link</a></li>
        <li><a href="#">Other one</a></li>
        <li><a href="#">Other one</a></li>
      </ul>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-6 <%= "col-sm-offset-3" unless current_user == @user %>">
      <div class="user-info">
        <% user_avatar_url = @user.facebook_picture_url || @user.photo %>

        <%= image_tag user_avatar_url, crop: :fill, class: "avatar-large" %>
        <h2><%= @user.first_name %></h2>
        <% @user.rating.times do %>
        <i class="fa fa-star active-star"></i>
        <% end %>
        <% (5 - @user.rating).times do %>
        <i class="fa fa-star inactive-star"></i>
        <% end %>
      </div>
      <div class="user-details">
        <h2>Bio</h2>
        <p><%= @user.bio %></p>
        <h2>Email</h2>
        <p><%= @user.email %></p>

        <div>
          <h2>Places</h2>
          <div class="row">
            <% @places.each do |place| %>
            <div class="col-xs-6 col-sm-12 col-md-6">
              <div class="card">
                <div class="card-category">
                  <% place.rating.times do %>
                  <i class="fa fa-star active-star"></i>
                  <% end %>
                  <% (5 - place.rating).times do %>
                  <i class="fa fa-star inactive-star"></i>
                  <% end %>
                </div>


                <div class="card-header" style="background-image: url('<%= cl_image_path place.photo, height: 300, width: 400, crop: :fill %>')">
                </div>


                <div class="card-description">
                <h3><%= place.name %></h3>
                <p>€<%= place.price %></p>
                </div>
                <%= link_to "", place_path(place), class: "card-link" %>
              </div>
            </div>
            <% end %>
          </div>
        </div>
        <h2>Reviews</h2>
        <% @user.reviews.each do |review| %>
        <% review.rating.times do %>
        <i class="fa fa-star active-star"></i>
        <% end %>
        <% (5 - review.rating).times do %>
        <i class="fa fa-star inactive-star"></i>
        <% end %>
        <p><%= review.content %></p>
        <% end %>
      </div>
    </div>
    <div class="col-xs-12 col-sm-6">
      <% if current_user == @user %>
      <div class="dashboard">
        <ul class="nav nav-tabs" role="tablist">
          <li role="presentation" class="active"><a href="#guests" data-toggle="tab">My guests</a>
          </li>
          <li role="presentation"><a href="#bookings"  data-toggle="tab">My bookings</a>
          </li>
        </ul>
        <div class="tab-content">
          <div role="tabpanel" class="tab-pane active" id="guests">
            <table class="table">
              <tr>
                <th>Guest</th>
                <th>Place</th>
                <th>Status</th>
              </tr>
              <% @reservations_for_me.each do |res| %>
              <tr>
                <td>
                  <%= link_to res.user.first_name, user_path(res.user) %>
                </td>
                <td>
                 <%= link_to res.place.name, place_path(res.place) %>
               </td>
               <td>
                <% if res.status == "pending" %>
                <%= link_to "Accept", reservation_accept_path(res.id), method: :patch, class: "btn btn-success" %> <%= link_to "Decline", reservation_decline_path(res.id), method: :patch, class: "btn btn-danger" %>
                <% elsif res.status == "accepted" %>
                <i class="fa fa-check"></i> Accepted
                <% elsif res.status == "declined" %>
                <i class="fa fa-times"></i> Declined
                <% end %>
              </td>
            </tr>
            <% end %>
          </table>
        </div>
        <div role="tabpanel" class="tab-pane" id="bookings">
          <table class="table">
            <tr>
              <th>Place</th>
              <th>Host</th>
              <th>Status</th>
            </tr>
            <% @reservations_i_made.each do |res| %>
            <tr>
              <td>
                <%= link_to res.place.name, place_path(res.place) %>
              </td>
              <td>
                <%= link_to res.place.user.first_name, user_path(res.place.user) %>
              </td>
              <td>
                <% if res.status == "accepted" %>
                <i class="fa fa-check"></i> Accepted
                <% elsif res.status == "declined" %>
                <i class="fa fa-times"></i> Declined
                <% else %>
                <i class="fa fa-question"></i> Pending
                <% end %>
              </td>
            </tr>
            <% end %>
          </table>
        </div>
      </div>


    </div>

    <% end %>
  </div>
</div>
</div>